### ISSUE TITLE
Setting *print-case* to :downcase affects names of layered function definers

### ISSUE THREAD

**Issue by darabi** [pcostanza/contextl#1]
I one of our systems, we had a `(setf *print-case* :downcase)` as a top-level form.
Using metacopy, the resulting layered copy method names are mixed case such as
```
metacopy-with-contextl::|=layered-function-definer-FOR-COPY-SELF=|
```
and subsequently lead to errors.

It would be desirable if the `*print-case*` chosen by the user wouldn't affect the
definer names.

**Comment by pcostanza** [comment]
Thanks a lot for reporting this issue. I believe I fixed this with the latest commit. Could you double-check this?

**Comment by darabi** [comment]
Sorry, I wanted to push the fix and create a PR immediately after opening the issue, but unfortunately the Day Job™ prevented that.

Yes thank you, your commit fixes the problem!
